---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    logLevel: debug
    provider: cloudflare
    cloudflare:
      email: calvin18@gmail.com
      secretName: external-dns-secret
      proxied: true
    domainFilters:
    - kelvinlaw.us
    # createSecret: true
    crd:
      create: true
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
