apiVersion: v1
stringData:
    api-token: ENC[AES256_GCM,data:xvT2OYzAh3xI3/LN0Qovw+jVZoL6yAEaf5SWy1nHsg+436do2WhH2g==,iv:i8LenRTTUByuh8cAJ+Hmce6I5m5XgWr1481n0w/jDTE=,tag:hTELWGyCIf2Ir56LwlknPA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-17T12:28:04Z'
    mac: ENC[AES256_GCM,data:zXsrxs3EUKyi1Yl2f1AyCtJwcJKgbntTxCBuX2+CAuEd3BS+mabzr8nJdPVRQs6Psa5EwESSw+OrJuoCg42HC7QorPTjQHZuyu2g2Q4TRId25IWXETuj4BtIwH7hN0/RdlC6YMTwFU56SdTKTKCCKQTFkrF2675niX2o+m81lOs=,iv:EMDuMaBE7Nuc20T8n6e6Qdy7H6tz7dQXGvRfKoc5tTU=,tag:TUV4HHoOEmM36dRAXrZ+eQ==,type:str]
    pgp:
    -   created_at: '2020-12-17T12:04:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAx3nQThvd9UGAQv9Ejp2S/TBOqu/8KSaL4O0/7MgJyg5SLknmRTvJOTsH48T
            hbG98+Cgh9tPhJ844nlsvhvEykrAcTUb186Al4ZFiVBH8TndhNgk41Uzhr6QjgFb
            zshIPPGH7rnwR1pk1qmiJpv0VemAPtTXVic16kY2tYcW9TJiwDlG7M3YQyjdteEZ
            gX0aAeP0BLxY7rNcdaZVWt2Wg2EuCZ8Gbw45qO03YGfbFl5YpSjc+vO3lPYLlhBB
            qfUZ+2dOcGwwVhcZMHXv+55qIq3aqmqChrOFaLIGE0zv5umdcb7MmmiWQlZBjjaT
            RWh14Pj5rJvMbx6W9ETHG+hvbiHhL1D+FI6dIQg9zn5RigSbBTr15Ev6DxHOW2s3
            wS9OqMJgC6ucjQHm88t8Dt9cQ0IfP+h/j4rSPKMVeKTxRVVkqP4p9DDGIcWcRw8z
            rRI3jcA5gbp4pJRfyvfpyRG8ufVXTkdVFdETLkZBOBxasm+lUd2uEPu5UwWb2lmo
            5hdS6mX5MiOKW/pPFAJy0l4BHVHXHvEnMfVydlXV+MA/tjbB+JId3P0Is5XdcPW2
            0hLu6zoZ1JZtkJyEobjrzVgcxcMwlPHfEuw+2QhW1I4ehkEuejGJ2GRr10ABSyLb
            KO9sErA66sONouYWyymr
            =tSzr
            -----END PGP MESSAGE-----
        fp: A12281A07AAE4D4C3DBE17AEB909564BC34C7D59
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
