apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stefanprodan.github.io/podinfo
      chart: podinfo
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: podinfo-charts
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    image:
      repository: ghcr.io/stefanprodan/podinfo
      pullPolicy: Always
      tag: 5.1.2
    service:
      type: NodePort
      nodePort: 30001